apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
spec:
  selector:
    matchLabels: 
      app: jenkins
  template: 
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:2.60.2
        ports:
          - containerPort: 8080
          - containerPort: 50000
