apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset12
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels: 
      app: jenkins
  template: 
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:2.60.2
        ports:
          - containerPort: 8080
          - containerPort: 50000
