apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: qa
spec:
  limits:
  - default:
      memory: 500Mi
      cpu: 1
    defaultRequest:
      memory: 200Mi
      cpu: 0.4  
    type: Container
