apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 3
      maxUnavailable: 0 
  selector:
    matchLabels: 
      app: jenkins
  template: 
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:2.60.2
        ports:
          - containerPort: 8080
          - containerPort: 50000
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: env
                operator: In
                values:
                - qa
                - prod
