apiVersion: apps/v1
kind: Deployment
metadata:
  name: jendep1
  labels: 
    apps: jenapps
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: jenapps
  template: 
    metadata:
      labels:
        app: jenapps
    spec:
      containers:
        - image: jenkins/jenkins:lts
          name: jendep
          tolerations:
           - key: "team"
             operator: "Equal"
             value: "devops"
             effect: "NoSchedule"
