apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: jenkins
  template: 
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
          - containerPort: 8080
          - containerPort: 50000
