apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-cpu-quota
  namespace: qa
spec: 
  hard:
   requests.cpu: "1"
   requests.memory: 1Gi
   limits.cpu: "2"
   limits.memory: 2Gi
   pods: 3  
