apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: docker push prabhakanth1995/kanth:tagname
  imagePullSecrets:
  - name: regcred


