apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-nodeport
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8080
      nodePort: 31000
  type: NodePort
